services:
  wiki:
    image: ghcr.io/labki-org/labki-platform:latest
    ports:
      - "8889:80"
    environment:
      MW_DB_HOST: db
      MW_DB_NAME: labki
      MW_DB_USER: labki
      MW_DB_PASSWORD: labki_pass
      MW_ADMIN_USER: Admin
      MW_ADMIN_PASS: dockerpass
      MW_DISABLE_PLATFORM_EXTENSIONS: 1
    volumes:
      - ./:/mw-user-extensions/StructureSync
      - ./tests/LocalSettings.test.php:/mw-config/LocalSettings.user.php
    depends_on:
      - db

  db:
    image: mariadb:10.11
    environment:
      MARIADB_DATABASE: labki
      MARIADB_USER: labki
      MARIADB_PASSWORD: labki_pass
      MARIADB_ROOT_PASSWORD: root_pass
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
